version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=crmuser
      - POSTGRES_PASSWORD=crmpass
      - POSTGRES_DB=crmdb
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: your-crm-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=crmuser
      - DB_PASS=crmpass
      - DB_NAME=crmdb
      # adicione aqui mais VARS de OCR, boleto, JWT etc
    depends_on:
      - db

volumes:
  db_data:
Adiciona docker-compose.yml
